name: Bug Report
description: Something within the app is not working as expected (files, app installation, etc...)
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        ## Device Information
  - type: dropdown
    attributes:
      label: Computer/Mobile Device Type
      description: What type of device are you using to run Dev Manager?
      options:
        - 'Windows'
        - 'macOS'
        - 'Linux'
        - 'Android'
  - type: input
    attributes:
      label: Dev Manager Version
      description: What is the version of Dev Manager you are using?
      placeholder: "Example: 1.99.8"
    validations:
      required: true
  - type: input
    attributes:
      label: webOS Model
      description: What is the model of your webOS device?
      placeholder: "Example: OLEDG4"
    validations:
      required: true
  - type: input
    attributes:
      label: webOS Version
      description: What is the webOS version of your device? Please don't confuse with the firmware version (XX.YY.ZZ).
      placeholder: "Example: webOS 4.5.3"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Rooted
      description: Is your webOS device rooted?
      options:
        - 'Yes'
        - 'No (with Dev Mode)'
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Host Information
        Please provide information about the computer you are streaming from.
        This information is important to reproduce the issue.
  - type: markdown
    attributes:
      value: |
        ## Issue Information
        Please provide information about the issue you are experiencing.
        This information is important to help us understand the issue.
  - type: textarea
    attributes:
      label: Bug Description
      description: What kind of incorrect behavior did you see?
      placeholder: "Example: I can't install apps on TV with Dev Manager."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Can you reproduce the issue? If so, please share below as steps.
      placeholder: |
        Example:
        1. Open Dev Manager
        2. Select "Available" section in Apps
        3. Click on "Install" button of an app
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What is the correct behavior do you think?
      placeholder: "The app should be installed on the TV."
