name: Feature Request
description: Suggest a new feature or improvement
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the feature you would like to have added.
      placeholder: "Example: I would like to add multiple apps repositories."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Why do you think this feature should be added?
      placeholder: "Example: I have multiple apps repositories and I want to see all the apps in one place."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "Example: My other repositories are..."
