[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-ls",
  "allow-read",
  "allow-write",
  "allow-mkdir",
  "allow-get",
  "allow-put",
  "allow-get-temp",
  "allow-serve"
]
